check for multiple definitions
demergent-labs/cdk_framework pull request #73
Opened 2023-05-12 21:33 UTC by bdemann

2023-05-12 21:43 UTC, lastmjs requested changes

2023-05-12 21:43 UTC, lastmjs commented on src/act/abstract_canister_tree.rs
> +            .chain(self.verify_type_refs_defs_are_unique().err())
fix

2023-05-12 21:43 UTC, lastmjs commented on src/act/abstract_canister_tree.rs
> +            .chain(self.verify_type_refs_defs_are_unique().err())
rename to type_defs

2023-05-12 21:43 UTC, lastmjs commented on src/act/abstract_canister_tree.rs
> +            .chain(self.verify_guard_functions_defs_are_unique().err())
guard_function_defs

2023-05-12 21:43 UTC, lastmjs commented on src/act/abstract_canister_tree.rs
> +fn find_duplicates<T: Eq + std::hash::Hash>(list: &[T]) -> Vec<&T> {
Immutable:

```rust
fn find_duplicates<T: Eq + Hash>(list: &[T]) -> Vec<&T> {
    let count_map = list.iter().fold(HashMap::new(), |mut acc, item| {
        *acc.entry(item).or_insert(0) += 1;
        acc
    });

    count_map
        .iter()
        .filter(|(_, &count)| count > 1)
        .map(|(&item, _)| item)
        .collect()
}
```

2023-05-12 21:43 UTC, lastmjs commented on src/act/abstract_canister_tree.rs
> +            .guard_functions
Implement `get_defined_names` on guard_functions, query methods, update methods, and anywhere else it makes sense

2023-05-12 21:43 UTC, lastmjs commented on src/act/abstract_canister_tree.rs
Expand to checking for all other duplicate-possible things

2023-05-12 22:37 UTC, bdemann commented on src/act/abstract_canister_tree.rs
- [x] Canister methods
     - [x] update
     - [x] query
     - [x] ~heartbeat~
     - [x] ~init~
     - [x] ~inspect~
     - [x] ~pre/post upgrade~
- [x] Candid types
- [x] guard functions

2023-05-12 22:38 UTC, bdemann commented on src/act/abstract_canister_tree.rs
for heartbeat, init, inspect, and pre/post upgrade, the cdk framework does not have access to the names used to define those. Everything else that does have a name is taken care of.

2023-05-13 00:31 UTC, lastmjs approved these changes

2023-05-13 00:37 UTC, merged