99 handle language keywords
demergent-labs/cdk_framework pull request #8
Opened 2022-11-29 20:32 UTC by bdemann

2022-11-29 21:20 UTC, dansteren commented on src/keyword.rs
> +pub fn to_regex(keywords: &Vec<String>) -> Vec<Regex> {
`to_regex` to me indicates that I will get one regex out. Consider changing this to `to_regex_list` (or something), or doing the mapping outside the function.

2022-11-29 21:25 UTC, lastmjs requested changes

2022-11-29 21:25 UTC, lastmjs commented on Cargo.toml
> +regex = "1"
Put a version

2022-11-29 21:25 UTC, lastmjs commented on src/abstract_canister_tree.rs
> +        let heartbeat_method = self.heartbeat_method.to_token_stream(context);
Use explicit unit type

2022-11-29 21:25 UTC, lastmjs commented on src/keyword.rs
> +            Regex::new(format!(r#"{}"#, keyword).as_str()).unwrap()
This won't even work at all

2022-11-29 21:25 UTC, lastmjs commented on src/keyword.rs
> +use regex::Regex;
Create an actual example with records and variants with all kinds of keywords

2022-11-29 21:25 UTC, lastmjs commented on src/lib.rs
> +impl<T: ToTokenStream<C>, C> ToTokenStream<C> for Option<T> {
Change C order

2022-11-29 21:25 UTC, lastmjs commented on src/nodes/act_canister_method.rs
> +    fn to_token_stream(&self, context: &Vec<String>) -> TokenStream {
When concretely specifying the context, use a descriptive variable name

2022-11-29 22:09 UTC, lastmjs requested changes

2022-11-29 22:09 UTC, lastmjs commented on src/nodes/act_external_canister/act_external_canister_method.rs
> +        canister_name: &String,
Implement the ToTokenStream trait and combine these params into one context struct

2022-11-29 22:09 UTC, lastmjs commented on src/nodes/act_heartbeat_method.rs
> +    fn to_token_stream(&self, _context: ()) -> TokenStream {
Just underscore

2022-11-29 22:09 UTC, lastmjs commented on src/nodes/act_inspect_message_method.rs
> +    fn to_token_stream(&self, _context: ()) -> TokenStream {
Just underscore

2022-11-29 22:09 UTC, lastmjs commented on src/nodes/act_pre_upgrade_method.rs
> +    fn to_token_stream(&self, _context: ()) -> TokenStream {
Just underscore

2022-11-29 22:09 UTC, lastmjs commented on src/nodes/data_type_nodes/act_funcs.rs
> +    fn to_token_stream(&self, _context: C) -> TokenStream {
Underscore only

2022-11-29 22:09 UTC, lastmjs commented on src/nodes/data_type_nodes/act_funcs.rs
> +impl ToTokenStream<&Vec<String>> for FuncTypeAlias {
Double-check that we aren't passing keyword_lists in where they aren't needed

2022-11-29 22:09 UTC, lastmjs commented on src/nodes/data_type_nodes/act_primitives.rs
> +    fn to_token_stream(&self, _context: C) -> TokenStream {
Underscore only

2022-11-30 17:52 UTC, lastmjs approved these changes

2022-11-30 17:52 UTC, merged